# ~/.config/lsd/config.yaml

# == Blocks ==
# This specifies the columns and their order when using the long and the tree
# layout.
# Possible values: permission, user, group, context, size, date, name, inode, links, git
blocks:
    - permission
    - user
    - size
    - date
    - name

# == Date ==
# This specifies the date format for the date column. The freeform format
# accepts a strftime like string.
# When "classic" is set, this is set to "date".
# Possible values: date, relative, '+<date_format>'
# `date_format` will be a `strftime` formatted value. e.g. `date: '+%d %b %y %X'` will give you a date like this: 17 Jun 21 20:14:55
date: "+%a %Y-%m-%d %H:%M:%S"

# == Sorting ==
sorting:
    # Specify what to sort by.
    # Possible values: extension, name, time, size, version
    column: name
    # Whether to reverse the sorting.
    # Possible values: false, true
    reverse: false
    # Whether to group directories together and where.
    # When "classic" is set, this is set to "none".
    # Possible values: first, last, none
    dir-grouping: first
