# Inserts a blank line between shell prompts
add_newline = false

format = """
$character\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[git_branch]
format = "[$symbol$branch]($style) "
